New IsFmt Signature
fetchrobotics/gojsonschema pull request #1
Opened 2019-07-19 22:48 UTC by Ferix9288

Updating xeipuuv 3rd party library to have better interface for FormatChecker.

## Limitations And Why

As of now, creating new custom FormatCheckers with `IsFormat` is very simplistic. Just return true or false. However, this results in the inability to modify the underlying local internal error that gets created. 

```go
		if !FormatCheckers.IsFormat(currentSubSchema.format, float64Value) {
			result.addInternalError(
				new(DoesNotMatchFormatError),
				context,
				value,
				ErrorDetails{"format": currentSubSchema.format},
			)
		}
```

My rather poor workaround is massaging the error like below:

```go
	for _, jsonPkgError := range result.Errors() {
		errType := jsonPkgError.Type()
		if errType == "number_one_of" || errType == "number_all_of" {
			continue
		}

		if errType == "format" {
			customizeToWFFormatError(jsonPkgError)
...

//customizeToWFFormatError will update description / message of a "DoesNotMatchFormatError" to WF-specific. There was no easy way to integrate with 3rd party library
//as it generically returns "DoesNotMatchFormatError" in the code.
func customizeToWFFormatError(jerr gojsonschema.ResultError) {
	match := formatRegExp.FindStringSubmatch(jerr.Description())
	if len(match) == 0 {
		return
	}
	fmtTypeStr := match[1]
	fmtType := customFmtType(fmtTypeStr)

	switch fmtType {
	case poseFmt:
		updatedMsg := fmt.Sprintf("Pose ID %v does not exist!", jerr.Value())
		jerr.SetDescription(updatedMsg)
	}
}

```

This is extremely limiting since it relies on regex on the actual format generic error string and also hardcodes what the error message should be. It could also be an internal error where the DB is down.

## Changing IsFormat Signature

Now, IsFormat function is as follows:

```go
	// FormatChecker is the interface all formatters added to FormatCheckerChain must implement
	FormatChecker interface {
		// IsFormat checks if input has the correct format and type. If not, return error.
		IsFormat(input interface{}) (bool, ResultError)
	}
```

Then, the callee can supply the appropriate `JSONContext`, `locale`, etc. to the `Results` list.

```
func applyFmtCheck(checkers *FormatCheckerChain, currentSubSchema *subSchema, value interface{}, result *Result, context *JsonContext) {
	if isRightFmt, err := checkers.IsFormat(currentSubSchema.format, value); !isRightFmt {
		existingDetails := err.Details()
		existingDetails["format"] = currentSubSchema.format
		result.addInternalError(
			err,
			context,
			value,
			existingDetails,
		)
	}
}
```

And internal IsFormat can become something like this: (note the flexibility of potentially differentiating among bad input, not found, and db error)

```go

type poseFormatError struct {
	gojsonschema.ResultErrorFields
}

func newPoseFormatError() *poseFormatError {
	err := new(poseFormatError)
	err.SetType("pose")
	err.SetDescriptionFormat("Pose ID {{.value}} cannot be found!")
	return err
}

//IsFormat implements gojsonschema.FormatChecker interface.
func (f poseFormatChecker) IsFormat(input interface{}) (bool, gojsonschema.ResultError) {

	rational, ok := input.(*big.Rat)
	if !ok {
		fmtErr := newPoseFormatError()
		fmtErr.SetDescriptionFormat("internal error: expecting big rational")
		return false, fmtErr
	}

	r := rational.Num()
	_, err := f.posePersister.Retrieve(uint(r.Int64()))

	//TODO: seperate NotFound vs DB error
	if err != nil {
		return false, newPoseFormatError()

	}
	return true, nil
}
```

2019-07-22 17:45 UTC, aselus-hub requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1)* status: all files reviewed, 1 unresolved discussion (waiting on @alexahnfetch, @calvinfeng, @ckrowl-fetch, @Ferix9288, and @yangchenyun)

*[a discussion](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-LkPlJkHCedbdCsfCWyo:-LkPlJkHCedbdCsfCWyp:b-gqgws1) (no related file):*
I don't think you need to remove the default one, should probably use it as the base for each copy, that way we don't haveto redefine the default validators.  

That does make me wonder: What is the reason for wanting to remove the general validators? Just switching the return value for all of them to be bool, nil is required, but shouldn't be that big of a deal? or is there something greater that i'm missing?

---


<!-- Sent from Reviewable.io -->

2019-07-22 18:27 UTC, Ferix9288 reviewed
> *[Reviewable](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1)* status: all files reviewed, 1 unresolved discussion (waiting on @alexahnfetch, @aselus-hub, @calvinfeng, @ckrowl-fetch, and @yangchenyun)

*[a discussion](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-LkPlJkHCedbdCsfCWyo:-LkPv96j8ApP6Rs_gY_I:b-s1ycfx) (no related file):*
<details><summary><i>Previously, aselus-hub (Alexei Kozlenok) wrote…</i></summary><blockquote>

I don't think you need to remove the default one, should probably use it as the base for each copy, that way we don't haveto redefine the default validators.  

That does make me wonder: What is the reason for wanting to remove the general validators? Just switching the return value for all of them to be bool, nil is required, but shouldn't be that big of a deal? or is there something greater that i'm missing?
</blockquote></details>

Problem is that even if I were to use the current `IsFormat` as a base and create a new method, it would still require code line change on all the default validators given the new interface method.

I rather just require everyone to make the appropriate function signature change. 

However, is your question more specifically about why I commented out all the default validators?  I do plan on fixing those but just wanted a quick proof of concept first before committing.

---


<!-- Sent from Reviewable.io -->

2019-07-22 18:32 UTC, Ferix9288 reviewed
> *[Reviewable](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1)* status: all files reviewed, 1 unresolved discussion (waiting on @alexahnfetch, @aselus-hub, @calvinfeng, @ckrowl-fetch, and @yangchenyun)

*[a discussion](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-LkPlJkHCedbdCsfCWyo:-LkPwGQcCZIGJFj4siuX:b-u2s0sc) (no related file):*
> However, is your question more specifically about why I commented out all the default validators?  I do plan on fixing those but just wanted a quick proof of concept first before committing.

But yes. In general, it's not big of a deal at all, and I plan on fixing them. : )

---


<!-- Sent from Reviewable.io -->

2019-07-23 00:44 UTC, aselus-hub approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-:-LkRHIfw-eokbbqFjdP5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alexahnfetch, @calvinfeng, @ckrowl-fetch, and @yangchenyun)



<!-- Sent from Reviewable.io -->

2019-07-23 01:52 UTC, yangchenyun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-:-LkRWwZuBn_EDubhwdNV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alexahnfetch, @calvinfeng, and @ckrowl-fetch)

___
*[format_checkers.go, line 115 at r2](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-LkRWlDi9gnZ6cjNpb_o:-LkRWlDi9gnZ6cjNpb_p:b-t7zomg) ([raw file](https://github.com/fetchrobotics/gojsonschema/blob/8f4733f49a8ad8a5c8a5c4bbb0ea444b2c644d17/format_checkers.go#L115)):*
> ```
> DateFormatChecker{}
> ```
What's the plan moving forward? Are we bridging the changes or the author would take care of it?
___
*[format_checkers.go, line 128 at r2](https://reviewable.io/reviews/fetchrobotics/gojsonschema/1#-LkRWW-mB-IpQrUmtITL:-LkRWW-mB-IpQrUmtITM:b-cw74db) ([raw file](https://github.com/fetchrobotics/gojsonschema/blob/8f4733f49a8ad8a5c8a5c4bbb0ea444b2c644d17/format_checkers.go#L128)):*
> ```
> convertToNewChecker
> ```
Poc?


<!-- Sent from Reviewable.io -->

2019-07-23 04:03 UTC, merged